#!/bin/sh

templates=$(dirname "$0")/templates

infrastructure=$1

if [ $# -ge 3 ]; then
  echo "Usage: $0 <aws|vsphere|warden> <path/to/stub>"
  exit 1
fi

shift

if [ "$infrastructure" != "aws" ] && \
   [ "$infrastructure" != "warden" ] && \
   [ "$infrastructure" != "vsphere" ] ; then
 echo "usage: ./generate_deployment_manifest <aws|warden|vsphere> [stubs...]"
 exit 1
fi

spiff merge \
 "$templates/cf-redis-deployment.yml" \
 "$templates/cf-infrastructure-$infrastructure.yml" \
 "$@"
