#!/bin/bash

set -e

BOSH_TARGET_ALIAS="lite"
WORKSPACE_BASE_DIR="$HOME/workspace"

log() {
  local _message=$1
  echo -e "$_message"
}

bosh_target_and_set_deployment() {
  local _bosh_target=$1
  local _bosh_deployment_manifest_path=$2

  bosh target "$_bosh_target"
  bosh deployment "$_bosh_deployment_manifest_path"
}

bosh_deploy() {
  bosh -n deploy
}

bosh_run_errand() {
  local _errand_name=$1

  bosh -n run errand "$_errand_name"
}

generate_manifest() {
  "$PWD"/scripts/generate-deployment-manifest \
  ~/workspace/london-ci-tools/manifests/redis/v424/ci-spiff/cf-redis-cs-jobs.yml \
  ~/workspace/london-ci-tools/manifests/redis/v424/ci-spiff/infrastructure-warden.yml \
  ~/workspace/london-ci-tools/manifests/redis/v424/ci-spiff/meta-warden.yml > "$BOSH_MANIFEST"
}

check_args() {
  if [ -z $BOSH_MANIFEST ]
  then
    export BOSH_MANIFEST=/tmp/redis-v424.yml
    generate_manifest
  fi

  if [ "$#" -lt 1 ]
  then
    log "[WARN] no BOSH target specified - defaulting to lite"
  else
    BOSH_TARGET_ALIAS=$1
  fi
}

update_release() {
  if [ ! -f scripts/update-release ]
  then
    log "Could not find scripts folder. Will run a submodule update."
    git submodule update --init --recursive
  else
    scripts/update-release
  fi
}

upload_release() {
  local _workdir=$1
  local _name=$2
  pushd "$_workdir"
  update_release
  bosh -n create release --force --name $_name
  bosh -n upload release --rebase || log "[WARN] Attempted a --rebase, but there were no job or package changes."
  popd
}

main() {
  check_args "$@"

  bosh_target_and_set_deployment "$BOSH_TARGET_ALIAS" "$BOSH_MANIFEST"

  upload_release "${WORKSPACE_BASE_DIR}/cf-redis-release" "cf-redis"

  bosh_deploy
  bosh_run_errand "broker-registrar"
}

main "$@"
