#!/bin/sh -e

BASE_DIR=$(cd $(dirname $0)/..; echo "$PWD")

templates=$BASE_DIR/templates

infrastructure=$1
additional_properties=$2
additional_properties_two=$4

if [ ! -z $3 ]; then
  stubs_dir=$3
else
  stubs_dir=$templates/sample_stubs
fi

if ! which spiff > /dev/null; then
  echo "Please install spiff (https://github.com/cloudfoundry-incubator/spiff#installation)"
  echo "before running this script"
  exit 1
fi

if [ "$infrastructure" != "aws" ] && \
   [ "$infrastructure" != "azure" ] && \
   [ "$infrastructure" != "warden" ] && \
   [ "$infrastructure" != "openstack" ] && \
   [ "$infrastructure" != "vsphere" ] ; then
 echo "usage: ${0} <aws|azure|warden|openstack|vsphere> [stubs...]"
 exit 1
fi

spiff merge \
 "$stubs_dir/infrastructure-$infrastructure.yml" \
 "$stubs_dir/meta-$infrastructure.yml" \
 $additional_properties_two \
  > generated-config.yml

spiff merge \
 "$templates/stubs/cf-redis-deployment.yml" \
 "$templates/stubs/cf-redis-jobs.yml" \
 "$templates/stubs/cf-redis-infrastructure.yml" \
 $additional_properties \
 "generated-config.yml"

rm generated-config.yml
