#!/bin/sh

BASE_DIR=$(cd "$(dirname \"$0\"/..)"; echo "$PWD")

templates=$BASE_DIR/templates

infrastructure=$1

which bosh > /dev/null 2>&1
if [ $? -ne 0 ]; then
  echo "Please install the bosh_cli ruby gem before running this script"
  exit 1
fi

if [ $# -lt 2 ]; then
  echo "Usage: $0 <aws|vsphere|warden> <path/to/stub>"
  exit 1
fi

shift

if [ "$infrastructure" != "aws" ] && \
   [ "$infrastructure" != "warden" ] && \
   [ "$infrastructure" != "vsphere" ] ; then
 echo "usage: ./generate_deployment_manifest <aws|warden|vsphere> [stubs...]"
 exit 1
fi

echo "director_uuid: $(bosh status --uuid)" > "$TMPDIR/director_uuid.yml"

spiff merge \
 "$templates/cf-redis-deployment.yml" \
 "$templates/cf-infrastructure-$infrastructure.yml" \
 "$@" \
 "$TMPDIR/director_uuid.yml"
