#!/bin/bash

set -e

log() {
  local _message=$1
  echo -e "$_message"
}

check_args() {
  if [ -z "$BOSH_MANIFEST" ]
  then
    log "Please set the BOSH_MANIFEST environment variable to the path to your manifest file"
    log "E.G. export BOSH_MANIFEST=/home/example/cf-redis-release/manifests/bosh-lite.yml"
    exit 1
  fi
}

check_args

IGNORE="\`initialize\'\: Object\#timeout is deprecated, use Timeout\.timeout instead\."
(bundle install && bundle exec rake spec 3>&1 1>&2 2>&3 | grep -v -p "$IGNORE") 3>&1 1>&2 2>&3
