#!/bin/bash

set -ex

if [ -z "$DOCKER_IMAGE" ]; then
  DOCKER_IMAGE=cflondonservices/london-services-ci-base
fi

[ -z "$BOSH_MANIFEST" ] && echo "Must set BOSH_MANIFEST environment variable" && exit 1;

manifest_dir=`dirname $BOSH_MANIFEST`
manifest_file=`basename $BOSH_MANIFEST`

docker_manifest_dir="/tmp/manifest"
docker_dir=/home/vcap/pivotal-product

pushd "$(dirname "$0")/.."
docker run \
  -e "BOSH_MANIFEST=$docker_manifest_dir/$manifest_file" \
  --rm --volume "$PWD":"$docker_dir" \
  --volume "$manifest_dir":"$docker_manifest_dir" \
  --workdir "$docker_dir" \
  "$DOCKER_IMAGE" \
  bash -c "bundle install && bundle exec rake spec"
popd
