---
meta: ~

# PROPERTIES
properties:
  <<: (( merge ))
  broker: (( .meta.broker ))
  cf: (( .meta.cf ))
  syslog_aggregator: (( .meta.syslog_aggregator ))
  redis:
    broker:
      auth:
        username: (( .meta.broker.username ))
        password: (( .meta.broker.password ))
      enable_service_access: true
      service_name: (( .meta.service_name ))
      route_name: (( .meta.route_name ))
      network: redis_z1
      backend_host: (( jobs.cf-redis-broker.networks.redis_z1.static_ips.[0] ))
      backend_port: 12345
      name: redis
      service_instance_limit: (( .meta.redis.shared_plan.instance_limit ))
      dedicated_nodes: (( jobs.dedicated-node.networks.redis_z1.static_ips ))
    maxmemory: (( .meta.redis.shared_plan.max_memory ))
    host: (( jobs.cf-redis-broker.networks.redis_z1.static_ips.[0] ))
    config_command: (( .meta.redis.config_command ))
    save_command: (( .meta.redis.save_command ))
    bg_save_command: (( .meta.redis.bg_save_command ))
    agent:
      backend_port: 54321

resource_pools: ~
networks: ~

# RELEASES
base_releases:
- name: (( .meta.release_name ))
  version: latest

additional_releases: (( merge || [] ))

releases: (( base_releases additional_releases ))


# JOBS
job_templates:
  cf_redis_broker:
  - name: cf-redis-broker
    release: (( .meta.release_name ))
  - name: syslog-configurator
    release: (( .meta.release_name ))
  dedicated_node:
  - name: dedicated-node
    release: (( .meta.release_name ))
  - name: syslog-configurator
    release: (( .meta.release_name ))
  broker_registrar:
  - name: broker-registrar
    release: (( .meta.release_name ))
  broker_deregistrar:
  - name: broker-deregistrar
    release: (( .meta.release_name ))
  smoke_tests:
  - name: smoke-tests
    release: (( .meta.release_name ))

additional_job_templates:
  cf_redis_broker: (( merge || [] ))
  dedicated_node: (( merge || [] ))
  broker_registrar: (( merge || [] ))
  broker_deregistrar: (( merge || [] ))
  smoke_tests: (( merge || [] ))

additional_job_properties:
  cf_redis_broker: (( merge || [] ))
  dedicated_node: (( merge || [] ))
  broker_registrar: (( merge || [] ))
  broker_deregistrar: (( merge || [] ))
  smoke_tests: (( merge || [] ))

jobs:
- instances: (( .meta.redis.dedicated_plan.instance_count ))
  name: dedicated-node
  networks:
  - name: redis_z1
    static_ips: (( merge || static_ips(0,1,2,3,4) ))
  persistent_disk: 4096
  resource_pool: (( .resource_pools.[0].name ))
  templates: (( job_templates.dedicated_node additional_job_templates.dedicated_node ))
  <<: (( merge ))
- instances: 1
  name: cf-redis-broker
  networks:
  - name: redis_z1
    static_ips: (( merge || static_ips(5) ))
  persistent_disk: 4096
  properties:
    redis:
      broker:
        subdomain: redis-broker-v346
  resource_pool: (( .resource_pools.[0].name ))
  templates: (( job_templates.cf_redis_broker additional_job_templates.cf_redis_broker ))
  <<: (( merge ))
- instances: 1
  lifecycle: errand
  name: broker-registrar
  networks:
  - name: redis_z1
  properties:
    broker:
      name: (( .properties.redis.broker.name || "redis" ))
      host: (( .properties.redis.broker.route_name "." .meta.apps_domain ))
      username: (( .properties.redis.broker.auth.username ))
      password: (( .properties.redis.broker.auth.password ))
  resource_pool: (( .resource_pools.[0].name ))
  templates: (( job_templates.broker_registrar additional_job_templates.broker_registrar ))
  <<: (( merge ))
- instances: 1
  lifecycle: errand
  name: broker-deregistrar
  networks:
  - name: redis_z1
  properties:
    broker:
      name: (( .properties.redis.broker.name || "redis" ))
      host: (( .properties.redis.broker.route_name "." .meta.apps_domain ))
      username: (( .properties.redis.broker.auth.username ))
      password: (( .properties.redis.broker.auth.password ))
  resource_pool: (( .resource_pools.[0].name ))
  templates: (( job_templates.broker_deregistrar additional_job_templates.broker_deregistrar ))
  <<: (( merge ))
- instances: 1
  lifecycle: errand
  name: smoke-tests
  networks:
  - name: redis_z1
  resource_pool: (( .resource_pools.[0].name ))
  templates: (( job_templates.smoke_tests additional_job_templates.smoke_tests ))
  <<: (( merge ))
